version: "3.9"
services:
  db:
    image: postgres:16
    container_name: sales_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres1122
      POSTGRES_PASSWORD: postgres1122
      POSTGRES_DB: sales
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_ui
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin12345678
    ports:
      - "5050:80"
    depends_on:
      - db

  redis:
    image: redis:7-alpine
    container_name: sales_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  postgres_data:
  redisdata: